import { useState } from "react";
import { Download, Edit3, Plus, Search, Trash2, Upload } from "lucide-react";
import { formatMoney } from "../../shared/money";
import { Empty, Modal, Stat } from "./components";
import { CustomerForm, PrinterForm, ProductForm, ShopForm } from "./forms";
import { useStore } from "./store";
import { useNavigate } from "react-router-dom";
export function Dashboard(){
 const s=useStore(),nav=useNavigate(),shop=s.shops.find(x=>x.id===s.settings.activeShopId)||s.shops[0],today=new Date().toDateString(),sales=s.sales.filter(x=>new Date(x.createdAt).toDateString()===today&&x.status==="completed"&&(!shop||x.shopId===shop.id));const total=sales.reduce((n,x)=>n+x.total,0);
 return <div className="max-w-[1280px] mx-auto"><div className="flex justify-between items-end mb-7"><div><p className="text-sm font-bold text-[#ff5f73] uppercase tracking-widest">Overview</p><h1 className="text-3xl font-black mt-1">Good {new Date().getHours()<12?"morning":new Date().getHours()<18?"afternoon":"evening"}.</h1><p className="text-[#737d79] mt-1">Here's what's happening at {shop?.name||"your shop"}.</p></div><button className="btn btn-primary" onClick={()=>nav("/sale")}><Plus size={17}/>Start a sale</button></div>
  {(!shop||!s.templates.length)&&<div className="surface p-4 mb-5 border-[#e2be72] bg-[#fff8e8] text-sm"><b>Setup needed.</b> {!shop?"Create your first shop.":"Add a receipt template before completing a sale."}</div>}
  <div className="grid grid-cols-4 gap-4"><Stat label="Today's sales" value={String(sales.length)}/><Stat label="Today's revenue" value={shop?formatMoney(total,shop.currency,shop.locale):"$0.00"} accent/><Stat label="Products" value={String(s.products.filter(x=>x.isActive).length)}/><Stat label="Printer" value={s.printers[0]?.name||"Not set"}/></div>
  <div className="grid grid-cols-[1.5fr_1fr] gap-5 mt-5"><div className="surface p-5"><div className="flex justify-between mb-4"><h2 className="font-bold">Recent sales</h2><button className="text-sm font-bold text-[#1e7165]" onClick={()=>nav("/sales")}>View all</button></div>{s.sales.length?<div className="divide-y">{[...s.sales].reverse().slice(0,6).map(x=><div key={x.id} className="py-3 flex justify-between"><div><p className="font-semibold">{x.receiptNumber}</p><p className="text-xs text-[#78827f]">{new Date(x.createdAt).toLocaleString()}</p></div><p className="font-bold">{shop?formatMoney(x.total,shop.currency,shop.locale):x.total}</p></div>)}</div>:<p className="text-sm text-[#78827f] py-8 text-center">Your completed sales will appear here.</p>}</div><div className="surface p-5"><h2 className="font-bold mb-4">Quick actions</h2><div className="space-y-2"><button className="btn w-full justify-start" onClick={()=>nav("/sale")}><Plus size={17}/>New sale</button><button className="btn w-full justify-start" onClick={()=>nav("/products")}><Plus size={17}/>Add product</button><button className="btn w-full justify-start" onClick={()=>nav("/printers")}>Printer settings</button></div></div></div>
 </div>
}
type Kind="products"|"customers"|"shops"|"printers";
const labels:{[K in Kind]:string}={products:"Products",customers:"Customers",shops:"Shops",printers:"Printers"};
export function EntityPage({kind}:{kind:Kind}){
 const s=useStore(),[query,setQuery]=useState(""),[editing,setEditing]=useState<any|false>(false),[testing,setTesting]=useState<any|false>(false),[testTemplateId,setTestTemplateId]=useState(""),[testBusy,setTestBusy]=useState(false),items=(s[kind] as any[]).filter(x=>(x.name||"").toLowerCase().includes(query.toLowerCase()));const shop=s.shops.find(x=>x.id===s.settings.activeShopId)||s.shops[0];
 const save=async(v:any)=>{await s.upsert(kind as any,v);setEditing(false)};const remove=async(id:string)=>{if(confirm("Delete this item? This cannot be undone."))await s.remove(kind,id)};
 return <div className="max-w-[1280px] mx-auto"><div className="flex justify-between items-end mb-6"><div><p className="text-sm font-bold text-[#ff5f73] uppercase tracking-widest">Manage</p><h1 className="text-3xl font-black">{labels[kind]}</h1></div><button className="btn btn-primary" onClick={()=>setEditing({})}><Plus size={17}/>Add {labels[kind].slice(0,-1).toLowerCase()}</button></div>
  <div className="surface"><div className="p-4 border-b flex justify-between"><div className="relative w-80"><Search size={17} className="absolute left-3 top-3 text-[#7a8581] pointer-events-none"/><input className="input !pl-10" placeholder={`Search ${kind}…`} value={query} onChange={e=>setQuery(e.target.value)}/></div>{kind==="products"&&<div className="flex gap-2"><button className="btn"><Upload size={16}/>Import CSV</button><button className="btn"><Download size={16}/>Export CSV</button></div>}</div>
  {!items.length?<div className="p-6"><Empty title={`No ${kind} yet`} detail={`Add your first ${labels[kind].slice(0,-1).toLowerCase()} to get started.`} action={<button className="btn btn-primary" onClick={()=>setEditing({})}><Plus size={16}/>Add one</button>}/></div>:<table className="w-full text-sm"><thead className="text-left text-xs uppercase tracking-wider text-[#77817e] bg-[#f7f7f3]"><tr><th className="p-4">Name</th><th className="p-4">{kind==="products"?"Category":kind==="printers"?"Connection":"Details"}</th><th className="p-4">{kind==="products"?"Price":kind==="printers"?"Paper":"Updated"}</th><th className="p-4 text-right">Actions</th></tr></thead><tbody className="divide-y">{items.map(x=><tr key={x.id} className="hover:bg-[#fafaf7]"><td className="p-4 font-bold">{x.name}<div className="text-xs text-[#7d8784] font-normal">{x.sku||x.email||x.legalName||(kind==="printers"?(x.printerType==="label"?"Label printer":"Receipt printer"):"")}</div></td><td className="p-4">{x.category||x.connectionType||x.phone||x.addressLines?.[0]||"—"}</td><td className="p-4">{kind==="products"&&shop?formatMoney(x.price,shop.currency,shop.locale):kind==="printers"?x.printerType==="label"?`${x.paperWidthMm} × ${x.paperHeightMm} mm`:`${x.paperWidthMm} mm`:new Date(x.updatedAt).toLocaleDateString()}</td><td className="p-4"><div className="flex justify-end gap-2">{kind==="printers"&&x.printerType!=="label"&&<button className="btn !py-1.5" onClick={()=>{setTesting(x);setTestTemplateId(shop?.defaultTemplateId||s.templates[0]?.id||"")}}>Print test</button>}<button className="btn !p-2" onClick={()=>setEditing(x)}><Edit3 size={15}/></button><button className="btn btn-danger !p-2" onClick={()=>void remove(x.id)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table>}</div>
  {editing&&<Modal title={`${editing.id?"Edit":"Add"} ${labels[kind].slice(0,-1)}`} onClose={()=>setEditing(false)}>{kind==="shops"?<ShopForm value={editing.id?editing:undefined} onSave={save}/>:kind==="products"?<ProductForm value={editing.id?editing:undefined} shopId={shop?.id} onSave={save}/>:kind==="customers"?<CustomerForm value={editing.id?editing:undefined} onSave={save}/>:<PrinterForm value={editing.id?editing:undefined} onSave={save}/>}</Modal>}
  {testing&&<Modal title={`Print test — ${testing.name}`} onClose={()=>!testBusy&&setTesting(false)}><p className="text-sm text-[#68736f] mb-5">Choose a saved receipt template. Receipt Studio will print it with sample customer and sale data through the same path used for real receipts. No sale will be saved.</p><label><span className="label">Receipt template</span><select autoFocus className="input" value={testTemplateId} onChange={e=>setTestTemplateId(e.target.value)}><option value="">Choose a template</option>{s.templates.map(template=><option key={template.id} value={template.id}>{s.shops.find(x=>x.id===template.shopId)?.name||"Shop"} — {template.name}</option>)}</select></label>{!s.templates.length&&<p className="text-sm text-red-600 mt-3">Create and save a receipt template before printing a test.</p>}<div className="flex justify-end gap-2 mt-6"><button className="btn" disabled={testBusy} onClick={()=>setTesting(false)}>Cancel</button><button className="btn btn-primary" disabled={!testTemplateId||testBusy} onClick={async()=>{setTestBusy(true);try{const result=await window.receiptStudio.printTemplateTest(testing.id,testTemplateId);alert(result.message||"Test receipt sent to printer.");setTesting(false)}catch(e:any){alert(e.message)}finally{setTestBusy(false)}}}>{testBusy?"Printing…":"Print selected template"}</button></div></Modal>}</div>
}
export function SettingsPage(){
 const s=useStore(),[method,setMethod]=useState("");const addMethod=async()=>{const value=method.trim();if(!value||s.settings.paymentMethods.some(x=>x.toLowerCase()===value.toLowerCase()))return;await s.setSettings({...s.settings,paymentMethods:[...s.settings.paymentMethods,value]});setMethod("")};return <div className="max-w-3xl mx-auto"><p className="text-sm font-bold text-[#ff5f73] uppercase tracking-widest">Application</p><h1 className="text-3xl font-black mb-7">Settings</h1><div className="surface divide-y"><section className="p-6"><h2 className="font-bold">Appearance</h2><p className="text-sm text-[#74807c] mb-4">Choose how Receipt Studio looks.</p><select className="input max-w-xs" value={s.settings.theme} onChange={e=>void s.setSettings({...s.settings,theme:e.target.value as any})}><option value="light">Light</option><option value="dark">Dark</option><option value="system">System</option></select></section><section className="p-6"><h2 className="font-bold">Payment methods</h2><p className="text-sm text-[#74807c] mb-4">These choices appear during checkout and on printed receipts.</p><div className="flex flex-wrap gap-2 mb-4">{s.settings.paymentMethods.map(item=><span key={item} className="inline-flex items-center gap-2 rounded-full bg-[#e7efec] px-3 py-1.5 text-sm font-semibold">{item}<button aria-label={`Remove ${item}`} disabled={s.settings.paymentMethods.length===1} onClick={()=>void s.setSettings({...s.settings,paymentMethods:s.settings.paymentMethods.filter(x=>x!==item)})} className="text-[#8d453d] disabled:opacity-30">×</button></span>)}</div><div className="flex gap-2 max-w-md"><input className="input" placeholder="e.g. bKash, Bank Transfer" value={method} onChange={e=>setMethod(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void addMethod()}}}/><button className="btn btn-primary" onClick={()=>void addMethod()}>Add</button></div></section><section className="p-6"><h2 className="font-bold">Backup & restore</h2><p className="text-sm text-[#74807c] mb-4">Export a complete copy of your local data or restore a validated backup.</p><div className="flex gap-2"><button className="btn" onClick={()=>void window.receiptStudio.exportBackup()}>Export backup</button><button className="btn" onClick={async()=>{if(confirm("Importing replaces current data after creating a safety backup. Continue?")){await window.receiptStudio.importBackup();await s.load()}}}>Import backup</button></div></section><section className="p-6"><h2 className="font-bold">Diagnostics</h2><p className="text-sm text-[#74807c] mb-4">Logs never include full customer or sales records.</p><div className="flex gap-2"><button className="btn" onClick={()=>void window.receiptStudio.openLogs()}>Open logs folder</button><button className="btn" onClick={async()=>{await window.receiptStudio.diagnostics();alert("Diagnostics copied")}}>Copy diagnostics</button></div></section></div></div>
}

