import { useMemo, useState } from "react";
import { Minus, Plus, Search, ShoppingBag, Trash2, Eye, Printer, FileDown } from "lucide-react";
import { formatMoney, lineTotals, saleTotals } from "../../shared/money";
import type { Sale, SaleItem } from "../../shared/schemas";
import { Empty, Modal } from "./components";
import { ReceiptPreview } from "./receiptPreview";
import { useStore } from "./store";
import { CustomerForm } from "./forms";
const now=()=>new Date().toISOString();
export function SalePage(){
 const s=useStore(),shop=s.shops.find(x=>x.id===s.settings.activeShopId)||s.shops[0],templates=s.templates.filter(x=>x.shopId===shop?.id),[templateId,setTemplateId]=useState(shop?.defaultTemplateId||templates[0]?.id||""),[printerId,setPrinterId]=useState(shop?.defaultPrinterId||s.printers[0]?.id||""),[items,setItems]=useState<SaleItem[]>([]),[search,setSearch]=useState(""),[discount,setDiscount]=useState(0),[customerId,setCustomerId]=useState(""),[payment,setPayment]=useState<Sale["paymentMethod"]>(s.settings.paymentMethods[0]||"Cash"),[paid,setPaid]=useState(""),[note,setNote]=useState(""),[preview,setPreview]=useState(false),[creatingCustomer,setCreatingCustomer]=useState(false),[busy,setBusy]=useState(false);
 const products=s.products.filter(p=>p.isActive&&(!shop||!p.shopIds.length||p.shopIds.includes(shop.id))&&(p.name+" "+(p.sku||"")+" "+(p.barcode||"")).toLowerCase().includes(search.toLowerCase()));
 const totals=useMemo(()=>saleTotals(items,discount),[items,discount]),customer=s.customers.find(x=>x.id===customerId),money=(n:number)=>formatMoney(n,shop?.currency,shop?.locale),template=s.templates.find(x=>x.id===templateId);
 const add=(p:any)=>setItems(old=>{const found=old.find(i=>i.productId===p.id);if(found)return old.map(i=>i.id===found.id?makeItem({...i,quantity:i.quantity+1}):i);return [...old,makeItem({id:crypto.randomUUID(),productId:p.id,name:p.name,sku:p.sku,quantity:1,unitPrice:p.price,discount:0,taxRate:p.taxRate||0})]});
 const update=(id:string,patch:Partial<SaleItem>)=>setItems(old=>old.map(i=>i.id===id?makeItem({...i,...patch}):i));
 const sale:Sale={id:crypto.randomUUID(),shopId:shop?.id||"",templateId,printerId:printerId||undefined,receiptNumber:"DRAFT",customerId:customer?.id,customerSnapshot:customer?{name:customer.name,phone:customer.phone,email:customer.email,address:customer.address}:undefined,items,subtotal:totals.subtotal,discount,tax:totals.tax,total:totals.total,paymentMethod:payment,amountPaid:paid?Math.round(Number(paid)*100):undefined,changeDue:paid?Math.max(0,Math.round(Number(paid)*100)-totals.total):undefined,note:note||undefined,status:"completed",printStatus:"not_printed",createdAt:now()};
 const complete=async(print:boolean)=>{if(!shop)return alert("Create a shop first.");if(!customer)return alert("Select a customer or create one with a phone number.");if(!templateId)return alert("Create or select a receipt template.");if(!items.length)return alert("Add at least one item.");setBusy(true);try{const result=await window.receiptStudio.completeSale(sale,print);await s.load();setItems([]);setDiscount(0);setPaid("");setCustomerId("");alert(print?result.print?.ok?"Sale saved and print data sent.":"Sale saved, but printing failed: "+result.print?.message:"Sale completed.");}catch(e:any){alert(e.message)}finally{setBusy(false)}};
 return <div className="h-full min-h-[690px] -m-7 grid grid-cols-[1fr_1.02fr_350px] bg-[#efeee8]">
  <section className="p-6 border-r border-[#d9d9d1] overflow-auto"><div className="flex items-center justify-between mb-5"><div><p className="text-xs uppercase tracking-widest font-bold text-[#b27e2c]">Catalog</p><h1 className="text-2xl font-black">New sale</h1></div><span className="text-xs bg-white px-3 py-1 rounded-full">{products.length} products</span></div><div className="relative mb-4"><Search size={17} className="absolute top-3 left-3 text-[#7d8783]"/><input data-product-search className="input pl-10" placeholder="Search name, SKU or barcode…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="grid grid-cols-2 gap-3">{products.map(p=><button key={p.id} onClick={()=>add(p)} className="surface p-4 text-left hover:border-[#3c8a7c] hover:-translate-y-0.5 transition"><div className="w-9 h-9 rounded-xl bg-[#e5eee9] flex items-center justify-center mb-6"><ShoppingBag size={17}/></div><p className="font-bold truncate">{p.name}</p><div className="flex justify-between mt-1 text-sm"><span className="text-[#7b8581]">{p.category||"General"}</span><span className="font-bold text-[#1c665b]">{money(p.price)}</span></div></button>)}</div>{!products.length&&<Empty title="No matching products" detail="Add products from the Products screen, or add a custom item."/>}</section>
  <section className="p-6 border-r border-[#d9d9d1] overflow-auto bg-[#f7f6f1]"><div className="flex justify-between mb-5"><h2 className="font-black text-xl">Current cart <span className="text-sm text-[#7e8885] font-normal">({items.length})</span></h2><button className="text-sm text-[#9a3d35]" onClick={()=>items.length&&confirm("Clear this cart?")&&setItems([])}>Clear</button></div>{!items.length?<Empty title="Your cart is empty" detail="Click a product to add it to this sale."/>:<div className="space-y-3">{items.map(i=><div className="surface p-4" key={i.id}><div className="flex justify-between gap-3"><input className="font-bold bg-transparent outline-none min-w-0 flex-1" value={i.name} onChange={e=>update(i.id,{name:e.target.value})}/><button onClick={()=>setItems(x=>x.filter(y=>y.id!==i.id))} className="text-[#a14c42]"><Trash2 size={16}/></button></div><div className="flex items-end gap-3 mt-3"><div><span className="label">Quantity</span><div className="flex items-center border rounded-lg bg-white"><button className="p-2" onClick={()=>update(i.id,{quantity:Math.max(.01,i.quantity-1)})}><Minus size={14}/></button><input className="w-10 text-center outline-none" type="number" value={i.quantity} onChange={e=>update(i.id,{quantity:Number(e.target.value)})}/><button className="p-2" onClick={()=>update(i.id,{quantity:i.quantity+1})}><Plus size={14}/></button></div></div><div className="w-24"><span className="label">Unit price</span><input className="input !p-2" type="number" step=".01" value={(i.unitPrice/100).toFixed(2)} onChange={e=>update(i.id,{unitPrice:Math.round(Number(e.target.value)*100)})}/></div><div className="w-20"><span className="label">Tax %</span><input className="input !p-2" type="number" value={i.taxRate} onChange={e=>update(i.id,{taxRate:Number(e.target.value)})}/></div><p className="ml-auto font-black pb-2">{money(i.lineTotal)}</p></div></div>)}</div>}<button className="btn w-full mt-3 border-dashed" onClick={()=>add({id:crypto.randomUUID(),name:"Custom item",price:0,taxRate:0})}><Plus size={15}/>Custom item</button></section>
  <aside className="p-6 bg-white overflow-auto"><h2 className="font-black text-xl mb-5">Checkout</h2><div className="space-y-4"><label><span className="label">Customer (required)</span><div className="flex gap-2"><select required className="input" value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Select customer</option>{s.customers.map(c=><option key={c.id} value={c.id}>{c.name?`${c.name} · ${c.phone}`:c.phone}</option>)}</select><button type="button" title="Create customer" className="btn !px-3" onClick={()=>setCreatingCustomer(true)}><Plus size={17}/></button></div></label><label><span className="label">Saved receipt template</span><select className="input" value={templateId} onChange={e=>setTemplateId(e.target.value)}><option value="">Select template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label><span className="label">Printer</span><select className="input" value={printerId} onChange={e=>setPrinterId(e.target.value)}><option value="">No printer</option>{s.printers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="border-y py-4 space-y-2 text-sm"><div className="flex justify-between"><span>Subtotal</span><b>{money(totals.subtotal)}</b></div><div className="flex justify-between items-center"><span>Discount</span><input className="input !w-24 !p-1.5 text-right" type="number" step=".01" value={(discount/100).toFixed(2)} onChange={e=>setDiscount(Math.round(Number(e.target.value)*100))}/></div><div className="flex justify-between"><span>Tax</span><b>{money(totals.tax)}</b></div><div className="flex justify-between text-xl pt-2"><b>Total</b><b>{money(totals.total)}</b></div></div><div className="grid grid-cols-2 gap-3"><label><span className="label">Payment</span><select className="input" value={payment} onChange={e=>setPayment(e.target.value)}>{s.settings.paymentMethods.map(method=><option key={method} value={method}>{method}</option>)}</select></label><label><span className="label">Amount paid</span><input className="input" type="number" step=".01" value={paid} onChange={e=>setPaid(e.target.value)}/></label></div>{paid&&<div className="flex justify-between bg-[#e5f1ed] p-3 rounded-xl text-sm"><span>Change due</span><b>{money(Math.max(0,Math.round(Number(paid)*100)-totals.total))}</b></div>}<textarea className="input" placeholder="Optional sale note" value={note} onChange={e=>setNote(e.target.value)}/><button className="btn w-full" onClick={()=>setPreview(true)}><Eye size={16}/>Preview receipt</button><button disabled={busy} className="btn btn-primary w-full !py-3" onClick={()=>void complete(true)}><Printer size={17}/>{busy?"Completing…":"Complete Sale & Print"}</button><button disabled={busy} className="btn w-full" onClick={()=>void complete(false)}>Complete without printing</button></div></aside>
  {preview&&<Modal wide title="Receipt preview" onClose={()=>setPreview(false)}><div className="bg-[#deddd6] p-8 flex justify-center"><ReceiptPreview template={template} sale={sale} shop={shop}/></div></Modal>}
  {creatingCustomer&&<Modal title="Create customer" onClose={()=>setCreatingCustomer(false)}><CustomerForm onSave={async value=>{await s.upsert("customers",value);setCustomerId(value.id);setCreatingCustomer(false)}}/></Modal>}
 </div>
}
function makeItem(input:any):SaleItem{const t=lineTotals(Number(input.quantity),input.unitPrice,input.discount||0,input.taxRate||0);return{...input,...t}}
export function SalesPage(){
 const s=useStore(),[query,setQuery]=useState(""),[view,setView]=useState<Sale|undefined>(),shop=s.shops.find(x=>x.id===s.settings.activeShopId)||s.shops[0],list=[...s.sales].reverse().filter(x=>x.receiptNumber.toLowerCase().includes(query.toLowerCase()));
 return <div className="max-w-[1280px] mx-auto"><p className="text-sm font-bold text-[#ff5f73] uppercase tracking-widest">Records</p><h1 className="text-3xl font-black mb-6">Sales history</h1><div className="surface"><div className="p-4 border-b relative w-full"><Search size={17} className="absolute left-7 top-7 text-[#7b8582]"/><input className="input pl-10 max-w-sm" placeholder="Search receipt number…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{!list.length?<div className="p-6"><Empty title="No completed sales" detail="Your first completed sale will be recorded here."/></div>:<table className="w-full text-sm"><thead className="text-left text-xs uppercase bg-[#f7f7f3] text-[#78827f]"><tr><th className="p-4">Receipt</th><th className="p-4">Date</th><th className="p-4">Items</th><th className="p-4">Payment</th><th className="p-4">Print</th><th className="p-4">Total</th><th/></tr></thead><tbody className="divide-y">{list.map(x=><tr key={x.id}><td className="p-4 font-bold">{x.receiptNumber}</td><td className="p-4">{new Date(x.createdAt).toLocaleString()}</td><td className="p-4">{x.items.length}</td><td className="p-4 capitalize">{x.paymentMethod}</td><td className="p-4"><span className={`rounded-full px-2 py-1 text-xs ${x.printStatus==="succeeded"?"bg-[#e0f0e9] text-[#17604f]":x.printStatus==="failed"?"bg-[#f9e4e1] text-[#9b4138]":"bg-[#eee]"}`}>{x.printStatus.replace("_"," ")}</span></td><td className="p-4 font-bold">{formatMoney(x.total,shop?.currency,shop?.locale)}</td><td className="p-4"><button className="btn !py-1.5" onClick={()=>setView(x)}>View</button></td></tr>)}</tbody></table>}</div>{view&&<Modal wide title={`Receipt ${view.receiptNumber}`} onClose={()=>setView(undefined)}><div className="grid grid-cols-[1fr_320px] gap-6"><div><h3 className="font-bold mb-3">Sale details</h3>{view.items.map(i=><div className="flex justify-between py-2 border-b" key={i.id}><span>{i.name} × {i.quantity}</span><b>{formatMoney(i.lineTotal,shop?.currency,shop?.locale)}</b></div>)}<div className="flex gap-2 mt-5"><button className="btn" onClick={async()=>{try{await window.receiptStudio.printSale(view.id);await s.load();alert("Print data sent.")}catch(e:any){alert(e.message)}}}><Printer size={16}/>Reprint</button><button className="btn" onClick={()=>void window.receiptStudio.exportPdf(view.id)}><FileDown size={16}/>Export PDF</button></div></div><ReceiptPreview template={s.templates.find(t=>t.id===view.templateId)} sale={view} shop={shop}/></div></Modal>}</div>
}

